camera_traj:
  ros__parameters:
    # Flags
    use_sim_time: false
    pure_local_trajectory: false
    debug_output: true

    # Topics
    depth_topic: "/zed/zed_node/depth/depth_registered"
    yolo_topic: "/cone_detection/output"
    camera_info_topic: "/zed/zed_node/depth/camera_info"
    rolling_map_debug_topic: "/camera_traj/debug/rolling_map"
    trajectory_debug_topic: "/camera_traj/debug/trajectory"
    output_topic: "/camera_traj/output"

    # Settings
    node_output_frequecy_hz: 15
    depth_extraction_algorithm: "bimodal"

    rolling_map_safety_threshold: 2.0
    rolling_map_ema_filter_alpha: 0.4
    rolling_map_hit_count_threshold: 1
    rolling_map_miss_count_threshold: 3
    camera_fov_rad: 1.9
    cull_distance_behind: -2.5
    cull_distance_max: 15.0

    delaunay_min_distance: 2.0
    delaunay_max_distance: 7.0

    spline_smoothing: 3.0
    spline_degree: 3
    spline_sampling_resolution: 0.5

    world_frame: "map"
    car_frame: "zed_camera_link"
