camera_traj:
  ros__parameters:
    # Flags
    use_sim_time: false
    pure_local_trajectory: false
    debug_output: true

    # Topics
    depth_topic: "/zed/zed_node/depth/depth_registered"
    yolo_topic: "/cone_detection/output"
    camera_info_topic: "/zed/zed_node/depth/camera_info"
    rolling_map_debug_topic: "/camera_traj/debug/rolling_map"
    trajectory_debug_topic: "/camera_traj/debug/trajectory"
    output_topic: "/camera_traj/output"

    mission_selected_topic: "/master/mission"
    mission_finish_topic: "/can_handler/to_can"

    # Settings
    node_output_frequecy_hz: 15
    depth_extraction_algorithm: "bimodal"
    trajectory_extension_meters: 5.0

    mission_finished_shutdown_cmd_delay_sec: 1.0
    mission_finished_lookback_meters: 0.0

    # DO NOT TOUCH, OVERWRITTEN BASED ON MISSION #
    target_laps: 1
    lap_cooldown_sec: 20.0
    lap_lateral_bound: 4.0

    max_lateral_acceleration: 5.0 # m/s
    max_speed: 5.0                # m/s
    min_speed: 4.0                # m/s
    # ############################################

    rolling_map_safety_threshold: 2.0
    rolling_map_ema_filter_alpha: 0.4
    rolling_map_hit_count_threshold: 2
    rolling_map_miss_count_threshold: 4
    camera_fov_rad: 1.9
    cull_distance_behind: -2.5
    cull_distance_max: 15.0

    delaunay_min_distance: 2.0
    delaunay_max_distance: 7.0

    spline_smoothing: 3.0
    spline_degree: 3
    spline_sampling_resolution: 0.5

    world_frame: "map"
    car_frame: "zed_camera_link"

    # Missions
    ebs_test:
      target_laps: 1
      lap_cooldown_sec: 2.0
      max_lateral_acceleration: 5.0
      max_speed: 13.0
      min_speed: 8.0

    acceleration:
      target_laps: 1
      lap_cooldown_sec: 2.0
      max_lateral_acceleration: 5.0
      max_speed: 13.0
      min_speed: 8.0

    autocross:
      target_laps: 1
      lap_cooldown_sec: 10.0
      max_lateral_acceleration: 5.0
      max_speed: 7.0
      min_speed: 6.0

    trackdrive:
      target_laps: 10
      lap_cooldown_sec: 10.0
      max_lateral_acceleration: 5.0
      max_speed: 10.0
      min_speed: 4.0
